[tool.poetry]
name = "tvhtokodi"
version = "0.1.1"
description = ""
authors = ["ccdale <chris.allison@hivehome.com>"]
readme = "README.md"
packages = [{include = "tvhtokodi", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
ccalogging = "^0.4.4"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
